### ISSUE TITLE
Error message when registering user that already exist

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#313]
This error message should be replaced with a message saying the user already is registered in the system.

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/per.kraulis/orderportal/account.py", line 655, in post
    raise tornado.web.HTTPError(400, reason=str(msg))
HTTPError: HTTP 400: email already in use

**Comment by pekrau** [comment]
Wrongly closed; reopen.
