### ISSUE TITLE
Fel när jag klickar på FORMS

### ISSUE THREAD

**Issue by VinnerePettersson** [pekrau/OrderPortal#318]
... från kontot där jag inte är admin, då får jag:

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 2601, in wrapper
    return method(self, *args, **kwargs)
  File "/home/per.kraulis/orderportal/form.py", line 84, in get
    self.check_admin()
  File "/home/per.kraulis/orderportal/requesthandler.py", line 115, in check_admin
    reason="you do not have role 'admin'")
HTTPError: HTTP 403: you do not have role 'admin'

//Olga

**Comment by pekrau** [comment]
The link "Form" should not appear when one is not admin.

**Comment by pekrau** [comment]
@VinnerePettersson exactly which page are you on when you click that Form link?

**Comment by pekrau** [comment]
Cannot be reproduced.
