### ISSUE TITLE
The f*cking file upload still does not work! utf-8 problem

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#452]
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 2601, in wrapper
    return method(self, *args, **kwargs)
  File "/home/per.kraulis/orderportal/file.py", line 139, in post
    saver['description'] = self.get_argument('description', None)
  File "/home/per.kraulis/orderportal/saver.py", line 49, in __exit__
    self.post_process()
  File "/home/per.kraulis/orderportal/file.py", line 37, in post_process
    content_type=self['content_type'])
  File "/usr/lib/python2.6/site-packages/couchdb/client.py", line 682, in put_attachment
    }, rev=doc['_rev'])
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 518, in put_json
    **params)
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 533, in _request_json
    headers=headers, **params)
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 529, in _request
    credentials=self.credentials)
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 313, in request
    resp = _try_request_with_retries(iter(self.retry_delays))
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 264, in _try_request_with_retries
    return _try_request()
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 290, in _try_request
    conn.endheaders(body)
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 62, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.6/site-packages/couchdb/http.py", line 69, in _send_output
    msg += message_body
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 10: invalid continuation byte

**Comment by pekrau** [comment]
The file attach to order works, doesn't it? Look at that.
