### ISSUE TITLE
Empty "University" field cause error when creating order

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#549]
If an account has an empty `University` field (user had left it blank and filled in the "other" field) this will throw this error when the user tried to create an order (when clicking create button after filling in order name):

```
Traceback (most recent call last): 
File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1332, in _execute 
result = method(*self.path_args, **self.path_kwargs) 
File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 2601, in wrapper 
return method(self, *args, **kwargs) 
File "/home/genomics.www/OrderPortal/orderportal/order.py", line 560, in post 
get(self.current_user.get('university', {})).get('fields', {}) 
AttributeError: 'NoneType' object has no attribute ‘get'

```

**Comment by pekrau** [comment]
The basic issue here is that it was at all possible to have an empty university field. Should not be allowed.
