### ISSUE TITLE
dump bug

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#885]
Does not write out entire db.

```
Traceback (most recent call last):
  File "cli.py", line 284, in <module>
    cli()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "cli.py", line 113, in dump
    attfile = db.get_attachment(doc, attname)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/couchdb2.py", line 796, in get_attachment
    params={"rev": doc["_rev"]})
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/couchdb2.py", line 245, in _GET
    self._check(response, errors=kwargs.get("errors", {}))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/couchdb2.py", line 295, in _check
    raise error(response.reason)
couchdb2.NotFoundError: Object Not Found
```

**Comment by pekrau** [comment]
Problem with order https://ngisweden.scilifelab.se/orders/order/NGI11600
One of the documents is missing?
